FROM {{ if .BaseRegistry }}{{ .BaseRegistry }}/{{ end }}node:22-alpine AS deps
WORKDIR /app
COPY package.json ./
RUN npm install

FROM {{ if .BaseRegistry }}{{ .BaseRegistry }}/{{ end }}node:22-alpine AS builder
USER root
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM {{ if .BaseRegistry }}{{ .BaseRegistry }}/{{ end }}node:22-alpine
WORKDIR /app
COPY --from=builder --chown=1000:1000 /app/.next/standalone ./
COPY --from=builder --chown=1000:1000 /app/.next/static ./.next/static

EXPOSE 3000
ENV HOSTNAME="0.0.0.0"
USER 1000
CMD ["node", "server.js"]
