FROM {{ if .BaseRegistry }}{{ .BaseRegistry }}/{{ end }}python:3.12-slim-bookworm
WORKDIR /app
COPY --chown=1000:1000 requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY --chown=1000:1000 . .
EXPOSE 8000
USER 1000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
